var mongoose = require('mongoose');

var defenseScehma = mongoose.Schema({
    team  : String,
    ruYds : Number,
    ruAtt : Number,
    paYds : Number,
    paAtt : Number,
    paCmp : Number,
    leAtt : Number,
    leYds : Number,
    ltAtt : Number,
    ltYds : Number,
    lgAtt : Number,
    lgYds : Number,
    mdAtt : Number,
    mdYds : Number,
    rgAtt : Number,
    rgYds : Number,
    rtAtt : Number,
    rtYds : Number,
    reAtt : Number,
    reYds : Number,
    qbAtt : Number,
    qbYds : Number,
    slAtt : Number,
    slYds : Number,
    smAtt : Number,
    smYds : Number,
    srAtt : Number,
    srYds : Number,
    dlAtt : Number,
    dlYds : Number,
    dmAtt : Number,
    dmYds : Number,
    drAtt : Number,
    drYds : Number,
    wr1At : Number,
    wr1Yd : Number,
    wr3At : Number,
    wr3Yd : Number,
    teAtt : Number,
    teYds : Number,
    rbAtt : Number,
    rbYds : Number
});

module.exports = mongoose.model('Defenses', defenseScehma);