var mongoose = require('mongoose');

var playerSchema = mongoose.Schema({
    _id: {},
    player: String,
    fname: String,
    lname: String,
    pname: String,
    pos1: String,
    pos2: String,
    height: Number,
    weight: Number,
    yob: Number,
    bench: Number,
    broad: Number,
    dpos: Number,
    col: String,
    dv: String,
    start: Number,
    cteam: String,
    posd: String,
    jnum: Number,
    dcp: Number,
    LEAtt: Number,
    LEYds: Number,
    LTAtt: Number,
    LTYds: Number,
    LGAtt: Number,
    LGYds: Number,
    MDAtt: Number,
    MDYds: Number,
    RGAtt: Number,
    RGYds: Number,
    RTAtt: Number,
    RTYds: Number,
    REAtt: Number,
    REYds: Number,
    DMAtt: Number,
    DMYds: Number,
    DRAtt: Number,
    DRYds: Number,
    SRAtt: Number,
    SRYds: Number,
    SMAtt: Number,
    SMYds: Number,
    SLAtt: Number,
    SLYds: Number,
    DLAtt: Number,
    DLYds: Number,
    gp: Number,
    def: String
});

var totalSchema = mongoose.Schema({
    team: String,
    gp: Number,
    TE1DMAtt: Number,
    TE1DMYds: Number,
    TE1DRAtt: Number,
    TE1DRYds: Number,
    TE1SRAtt: Number,
    TE1SRYds: Number,
    TE1SMAtt: Number,
    TE1SMYds: Number,
    TE1SLAtt: Number,
    TE1SLYds: Number,
    TE1DLAtt: Number,
    TE1DLYds: Number,
    TE2DMAtt: Number,
    TE2DMYds: Number,
    TE2DRAtt: Number,
    TE2DRYds: Number,
    TE2SRAtt: Number,
    TE2SRYds: Number,
    TE2SMAtt: Number,
    TE2SMYds: Number,
    TE2SLAtt: Number,
    TE2SLYds: Number,
    TE2DLAtt: Number,
    TE2DLYds: Number,
    TE3DMAtt: Number,
    TE3DMYds: Number,
    TE3DRAtt: Number,
    TE3DRYds: Number,
    TE3SRAtt: Number,
    TE3SRYds: Number,
    TE3SMAtt: Number,
    TE3SMYds: Number,
    TE3SLAtt: Number,
    TE3SLYds: Number,
    TE3DLAtt: Number,
    TE3DLYds: Number,
    TE4DMAtt: Number,
    TE4DMYds: Number,
    TE4DRAtt: Number,
    TE4DRYds: Number,
    TE4SRAtt: Number,
    TE4SRYds: Number,
    TE4SMAtt: Number,
    TE4SMYds: Number,
    TE4SLAtt: Number,
    TE4SLYds: Number,
    TE4DLAtt: Number,
    TE4DLYds: Number,
    LWR1DMAtt: Number,
    LWR1DMYds: Number,
    LWR1DRAtt: Number,
    LWR1DRYds: Number,
    LWR1SRAtt: Number,
    LWR1SRYds: Number,
    LWR1SMAtt: Number,
    LWR1SMYds: Number,
    LWR1SLAtt: Number,
    LWR1SLYds: Number,
    LWR1DLAtt: Number,
    LWR1DLYds: Number,
    LWR2DMAtt: Number,
    LWR2DMYds: Number,
    LWR2DRAtt: Number,
    LWR2DRYds: Number,
    LWR2SRAtt: Number,
    LWR2SRYds: Number,
    LWR2SMAtt: Number,
    LWR2SMYds: Number,
    LWR2SLAtt: Number,
    LWR2SLYds: Number,
    LWR2DLAtt: Number,
    LWR2DLYds: Number,
    LWR3DMAtt: Number,
    LWR3DMYds: Number,
    LWR3DRAtt: Number,
    LWR3DRYds: Number,
    LWR3SRAtt: Number,
    LWR3SRYds: Number,
    LWR3SMAtt: Number,
    LWR3SMYds: Number,
    LWR3SLAtt: Number,
    LWR3SLYds: Number,
    LWR3DLAtt: Number,
    LWR3DLYds: Number,
    LWR4DMAtt: Number,
    LWR4DMYds: Number,
    LWR4DRAtt: Number,
    LWR4DRYds: Number,
    LWR4SRAtt: Number,
    LWR4SRYds: Number,
    LWR4SMAtt: Number,
    LWR4SMYds: Number,
    LWR4SLAtt: Number,
    LWR4SLYds: Number,
    LWR4DLAtt: Number,
    LWR4DLYds: Number,
    RWR1DMAtt: Number,
    RWR1DMYds: Number,
    RWR1DRAtt: Number,
    RWR1DRYds: Number,
    RWR1SRAtt: Number,
    RWR1SRYds: Number,
    RWR1SMAtt: Number,
    RWR1SMYds: Number,
    RWR1SLAtt: Number,
    RWR1SLYds: Number,
    RWR1DLAtt: Number,
    RWR1DLYds: Number,
    RWR2DMAtt: Number,
    RWR2DMYds: Number,
    RWR2DRAtt: Number,
    RWR2DRYds: Number,
    RWR2SRAtt: Number,
    RWR2SRYds: Number,
    RWR2SMAtt: Number,
    RWR2SMYds: Number,
    RWR2SLAtt: Number,
    RWR2SLYds: Number,
    RWR2DLAtt: Number,
    RWR2DLYds: Number,
    RWR3DMAtt: Number,
    RWR3DMYds: Number,
    RWR3DRAtt: Number,
    RWR3DRYds: Number,
    RWR3SRAtt: Number,
    RWR3SRYds: Number,
    RWR3SMAtt: Number,
    RWR3SMYds: Number,
    RWR3SLAtt: Number,
    RWR3SLYds: Number,
    RWR3DLAtt: Number,
    RWR3DLYds: Number,
    RWR4DMAtt: Number,
    RWR4DMYds: Number,
    RWR4DRAtt: Number,
    RWR4DRYds: Number,
    RWR4SRAtt: Number,
    RWR4SRYds: Number,
    RWR4SMAtt: Number,
    RWR4SMYds: Number,
    RWR4SLAtt: Number,
    RWR4SLYds: Number,
    RWR4DLAtt: Number,
    RWR4DLYds: Number,
    SWR1DMAtt: Number,
    SWR1DMYds: Number,
    SWR1DRAtt: Number,
    SWR1DRYds: Number,
    SWR1SRAtt: Number,
    SWR1SRYds: Number,
    SWR1SMAtt: Number,
    SWR1SMYds: Number,
    SWR1SLAtt: Number,
    SWR1SLYds: Number,
    SWR1DLAtt: Number,
    SWR1DLYds: Number,
    SWR2DMAtt: Number,
    SWR2DMYds: Number,
    SWR2DRAtt: Number,
    SWR2DRYds: Number,
    SWR2SRAtt: Number,
    SWR2SRYds: Number,
    SWR2SMAtt: Number,
    SWR2SMYds: Number,
    SWR2SLAtt: Number,
    SWR2SLYds: Number,
    SWR2DLAtt: Number,
    SWR2DLYds: Number,
    SWR3DMAtt: Number,
    SWR3DMYds: Number,
    SWR3DRAtt: Number,
    SWR3DRYds: Number,
    SWR3SRAtt: Number,
    SWR3SRYds: Number,
    SWR3SMAtt: Number,
    SWR3SMYds: Number,
    SWR3SLAtt: Number,
    SWR3SLYds: Number,
    SWR3DLAtt: Number,
    SWR3DLYds: Number,
    SWR4DMAtt: Number,
    SWR4DMYds: Number,
    SWR4DRAtt: Number,
    SWR4DRYds: Number,
    SWR4SRAtt: Number,
    SWR4SRYds: Number,
    SWR4SMAtt: Number,
    SWR4SMYds: Number,
    SWR4SLAtt: Number,
    SWR4SLYds: Number,
    SWR4DLAtt: Number,
    SWR4DLYds: Number,
    LEAtt    : Number,
    LEYds    : Number,
    LTAtt    : Number,
    LTYds    : Number,
    LGAtt    : Number,
    LGYds    : Number,
    MDAtt    : Number,
    MDYds    : Number,
    RGAtt    : Number,
    RGYds    : Number,
    RTAtt    : Number,
    RTYds    : Number,
    REAtt    : Number,
    REYds    : Number,
    DMAtt    : Number,
    DMYds    : Number,
    DRAtt    : Number,
    DRYds    : Number,
    SRAtt    : Number,
    SRYds    : Number,
    SMAtt    : Number,
    SMYds    : Number,
    SLAtt    : Number,
    SLYds    : Number,
    DLAtt    : Number,
    DLYds    : Number
})

module.exports = {
    player: mongoose.model('player', playerSchema, 'player'),
    total : mongoose.model('total', totalSchema, 'total')
};